name: CI/CD Pipeline - Windows - CMake & Qt5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Qt5 environment
        shell: powershell
        run: |
          choco install -y qt5-default cmake
          $env:QT5_DIR = 'C:\tools\Qt5\5.15.2\msvc2019_64'
          echo "QT5_DIR=$env:QT5_DIR" >> $env:GITHUB_ENV

      - name: Configure CMake
        shell: cmd
        run: cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_PREFIX_PATH=%QT5_DIR%\lib\cmake

      - name: Build
        shell: cmd
        run: cmake --build build --config Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: build-artifact
          path: build
