name: CI/CD Pipeline - Windows - CMake & Qt5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VER: '5.15.2'
      QT_VER_MSVC: 'msvc2019_64'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Qt5 environment
        shell: pwsh
        run: |
          echo "QTDIR=C:\Qt\${{ env.QT_VER }}\${{ env.QT_VER_MSVC }}_64" >> ${{ github.env }}

      - name: Configure CMake
        shell: cmd
        run: cmake -S . -B build -G "Ninja" -DQt5_DIR=%QTDIR%

      - name: Build
        shell: cmd
        run: cmake --build build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: build-artifact
          path: build
